### ISSUE TITLE
Version Update 

### ISSUE THREAD

**Issue by SchemeSonic** [Paraboly/pwc-color-picker#2]
Before releasing v0.6 we should fix following issues:

- [ ] Remove unnecessary dependencies from component. 
https://www.npmjs.com/package/@paraboly/pwc-color-picker
Dependencies (2): @simonwep/pickr@types/jest

- [x] Add solid border and maybe box-shadow to pickers so than transparent color can be seen

**Comment by WrathChaos** [comment]
@sevvaleygul0

**Comment by WrathChaos** [comment]
@sevvaleygul0 Have you fixed these issues on the 0.0.8 release?
